# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234939cd21631491c1416929f2cb99089c882362aa5b0beb3a1d8a7dc3bc3414e7a8d99638f90294cf9732a258bd286e6265ca880eb8b35df8c875281f6fca32

test:
  secret_key_base: cbd84b5f17aae622a1b1f3c582d8054990d3ab8262accb0e8e6a8d94f8bb9d04b71fc00db2b87c0fd980c922f26237ccad02441a5ab5a6dd9638b00d4dfebdfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
